<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="DESKTOP-BQRCULL" name="Org.testngDemo.DemoGroups" tests="7" failures="1" timestamp="18 Mar 2021 08:33:30 GMT" time="0.016" errors="0">
  <testcase name="TC_02" time="0.000" classname="Org.testngDemo.DemoGroups">
    <skipped/>
  </testcase> <!-- TC_02 -->
  <testcase name="TC_04" time="0.000" classname="Org.testngDemo.DemoGroups">
    <skipped/>
  </testcase> <!-- TC_04 -->
  <testcase name="TC_01" time="0.012" classname="Org.testngDemo.DemoGroups">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at Org.testngDemo.DemoGroups.TC_01(DemoGroups.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC_01 -->
  <testcase name="TC_05" time="0.002" classname="Org.testngDemo.DemoGroups"/>
  <testcase name="TC_07" time="0.000" classname="Org.testngDemo.DemoGroups">
    <skipped/>
  </testcase> <!-- TC_07 -->
  <testcase name="TC_03" time="0.002" classname="Org.testngDemo.DemoGroups"/>
  <testcase name="TC_06" time="0.000" classname="Org.testngDemo.DemoGroups">
    <skipped/>
  </testcase> <!-- TC_06 -->
</testsuite> <!-- Org.testngDemo.DemoGroups -->
